(function(){
'use strict';
var $=function(id){return document.getElementById(id)};
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function hasToken(){return !!localStorage.getItem('mediswiftToken')}
async function req(ep,opt){if(window.mediswiftBackend&&window.mediswiftBackend.request)return window.mediswiftBackend.request(ep,opt||{});return window.apiRequest(ep,opt||{})}
function hide(id){var x=$(id);if(x)x.style.display='none'}
function msg(id,t){var x=$(id);if(x){x.textContent=t;x.style.display='block'}}
function closeProfile(){hide('profileModal')} function closeAppt(){hide('appointmentModal')}
function tab(name){document.querySelectorAll('.profile-tab').forEach(function(b){b.classList.toggle('active',b.dataset.profileTab===name)});document.querySelectorAll('.profile-pane').forEach(function(p){p.classList.remove('active')});var p=$('profilePane'+name[0].toUpperCase()+name.slice(1));if(p)p.classList.add('active');if(name==='appointments')loadAppointments();if(name==='orders')loadOrders()}
async function loadProfile(){var d=await req('/profile'),u=d.user||{};$('profileName').value=u.name||'';$('profileEmail').value=u.email||'';$('profilePhone').value=u.phone||'';$('profileAddress').value=u.address||'';$('profileCity').value=u.city||'';$('profilePincode').value=u.pincode||'';$('profileAvatarLarge').textContent=(u.name||'U')[0].toUpperCase();$('profileHeading').textContent=u.name||'My Profile';$('profileMemberSince').textContent=u.createdAt?'Member since '+new Date(u.createdAt).toLocaleDateString(undefined,{month:'long',year:'numeric'}):'Manage your MediSwift account';return u}
async function openProfile(which){if(!hasToken()){window.openModal('loginModal');return}$('profileModal').style.display='flex';tab(which||'details');hide('profileFormError');hide('profileFormSuccess');try{await loadProfile()}catch(e){closeProfile();alert('Could not load profile: '+e.message)}}
window.openMediSwiftProfile=openProfile;
async function loadAppointments(){var r=$('profileAppointments');r.innerHTML='<p class="profile-empty">Loading appointments…</p>';try{var d=await req('/appointments'),a=(d.appointments||[]).slice().reverse();r.innerHTML=a.length?a.map(function(x){return '<div class="profile-list-card"><div><h4>'+esc(x.doctorName||'Doctor')+'</h4><p>'+esc(x.date)+' at '+esc(x.time)+'</p>'+(x.reason?'<p>Reason: '+esc(x.reason)+'</p>':'')+'<span class="status-pill">'+esc(x.status||'Booked')+'</span></div>'+(x.status!=='Cancelled'?'<button class="btn btn-secondary" data-cancel-appointment="'+esc(x.id)+'">Cancel</button>':'')+'</div>'}).join(''):'<p class="profile-empty">No appointments yet.</p>'}catch(e){r.innerHTML='<p class="profile-empty">Could not load appointments.</p>'}}
async function loadOrders(){var r=$('profileOrders');r.innerHTML='<p class="profile-empty">Loading orders…</p>';try{var d=await req('/orders'),o=(d.orders||[]).slice().reverse();r.innerHTML=o.length?o.map(function(x){var c=(x.items||[]).reduce(function(n,i){return n+(Number(i.quantity)||1)},0);return '<div class="profile-list-card"><div><h4>Order '+esc(x.id)+'</h4><p>'+c+' item(s) • ₹'+esc(Number(x.total||0).toFixed(0))+'</p><p>'+esc(new Date(x.date).toLocaleString())+'</p><span class="status-pill">'+esc(x.status||'Order Received')+'</span></div><a class="btn btn-secondary" href="#tracking" data-close-profile="1">Track</a></div>'}).join(''):'<p class="profile-empty">No orders yet.</p>'}catch(e){r.innerHTML='<p class="profile-empty">Could not load orders.</p>'}}
window.openDoctorBooking=function(id){if(!hasToken()){window.openModal('loginModal');return}var d=typeof doctors!=='undefined'?doctors.find(function(x){return x.id===id}):null;if(!d){alert('Doctor details could not be loaded.');return}$('appointmentDoctorId').value=d.id;$('appointmentDoctorName').textContent=d.name+' • '+d.specialization+' • ₹'+d.consultationFee;var now=new Date(),today=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,10);$('appointmentDate').min=today;$('appointmentDate').value=today;$('appointmentTime').value='';$('appointmentReason').value='';hide('appointmentFormError');hide('appointmentFormSuccess');$('appointmentModal').style.display='flex'};
function mobile(){if(!hasToken())return;var d=document.querySelector('.mobile-menu-divider');if(!d)return;d.innerHTML='<button class="btn btn-secondary mobile-menu-btn-full" id="mobileProfileBtn">My Profile</button><button class="btn btn-ghost mobile-menu-btn-full" style="color:var(--red-600)" id="mobileLogoutBtn">Logout</button>';$('mobileProfileBtn').onclick=function(){window.closeMobileMenu();openProfile('details')};$('mobileLogoutBtn').onclick=function(e){window.logoutUser(e)}}
if(typeof window.loginUser==='function'){var prev=window.loginUser;window.loginUser=function(a){prev(a);mobile()}}
document.addEventListener('DOMContentLoaded',function(){
 $('myProfileBtn').onclick=function(e){e.preventDefault();openProfile('details')};$('profileCloseBtn').onclick=closeProfile;$('appointmentCloseBtn').onclick=closeAppt;
 document.querySelectorAll('.profile-tab').forEach(function(b){b.onclick=function(){tab(b.dataset.profileTab)}});
 $('profileModal').onclick=function(e){if(e.target===$('profileModal'))closeProfile()};$('appointmentModal').onclick=function(e){if(e.target===$('appointmentModal'))closeAppt()};
 $('profileForm').onsubmit=async function(e){e.preventDefault();hide('profileFormError');hide('profileFormSuccess');try{var d=await req('/profile',{method:'PUT',body:JSON.stringify({name:$('profileName').value.trim(),email:$('profileEmail').value.trim(),phone:$('profilePhone').value.trim(),address:$('profileAddress').value.trim(),city:$('profileCity').value.trim(),pincode:$('profilePincode').value.trim()})});window.loginUser(d.user);$('profileAvatarLarge').textContent=d.user.name[0].toUpperCase();$('profileHeading').textContent=d.user.name;msg('profileFormSuccess',d.message)}catch(x){msg('profileFormError',x.message)}};
 $('passwordForm').onsubmit=async function(e){e.preventDefault();hide('passwordFormError');hide('passwordFormSuccess');if($('newPassword').value!==$('confirmPassword').value){msg('passwordFormError','New passwords do not match.');return}try{var d=await req('/change-password',{method:'POST',body:JSON.stringify({currentPassword:$('currentPassword').value,newPassword:$('newPassword').value})});$('passwordForm').reset();msg('passwordFormSuccess',d.message)}catch(x){msg('passwordFormError',x.message)}};
 $('profileLogoutBtn').onclick=function(e){closeProfile();window.logoutUser(e)};
 $('profileAppointments').onclick=async function(e){var b=e.target.closest('[data-cancel-appointment]');if(!b)return;b.disabled=true;try{await req('/appointments/'+encodeURIComponent(b.dataset.cancelAppointment),{method:'DELETE'});await loadAppointments()}catch(x){b.disabled=false;alert(x.message)}};
 $('profileOrders').onclick=function(e){if(e.target.closest('[data-close-profile]'))closeProfile()};
 $('appointmentForm').onsubmit=async function(e){e.preventDefault();hide('appointmentFormError');hide('appointmentFormSuccess');var id=$('appointmentDoctorId').value,d=typeof doctors!=='undefined'?doctors.find(function(x){return x.id===id}):null;try{var out=await req('/appointments',{method:'POST',body:JSON.stringify({doctorId:id,doctorName:d?d.name:'',date:$('appointmentDate').value,time:$('appointmentTime').value,reason:$('appointmentReason').value.trim()})});msg('appointmentFormSuccess',out.message);setTimeout(function(){closeAppt();openProfile('appointments')},600)}catch(x){msg('appointmentFormError',x.message)}};
 var fr=$('finalRegisterBtn');if(fr)fr.onclick=function(e){e.preventDefault();hasToken()?openProfile('details'):window.openModal('registerModal')};
 document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeProfile();closeAppt()}});setTimeout(mobile,350);
});
})();
